apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t8uooadxy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t8uooadxy-nodejs 
  name: t8uooadxy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: t8uooadxy-nodejs 
